# Driver
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Connection string
db.url=jdbc:sqlserver://DESKTOP-EU216N6;instanceName=THAIBAO;databaseName=QuanLiKTX;encrypt=true;trustServerCertificate=true;
db.user=sa
db.password=123456

# HikariCP Connection Pool
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeout=30000
db.pool.idleTimeout=600000
db.pool.maxLifetime=1800000